import type { ColorTheme } from '../typescript/types.d.ts';
import color, { type ColorInstance } from 'color';

export function colorTheme(theme: ColorTheme) {
  const { terminal, tokens } = theme.colors;
  const text = color(theme.colors.text);
  const background = color(theme.colors.background);
  const primary = color(theme.colors.primary);
  const secondary = color(theme.colors.secondary);
  const error = color(theme.colors.error);
  const warning = color(theme.colors.warning);
  const info = color(theme.colors.info);
  const debug = color(theme.colors.debug);
  const added = color(theme.colors.added);
  const deleted = color(theme.colors.deleted);
  const modified = color(theme.colors.modified);

  const shadow = color('#000000')
    .alpha(background.isLight() ? 0.04 : 0.16)
    .hexa();

  const contrast = (value: ColorInstance) =>
    value.isLight() ? color('#000000') : color('#ffffff');

  const ease = (value: ColorInstance, adjust: number) =>
    value.isLight() ? value.mix(color('#000000'), adjust) : value.mix(color('#ffffff'), adjust);

  // TODO
  const DEBUG = color('#ff0000').hex();

  return {
    name: theme.label,
    colors: {
      // Contrast Colors - see: https://code.visualstudio.com/api/references/theme-color#contrast-colors
      // 'contrastActiveBorder': undefined,
      // 'contrastBorder': undefined,

      // Base Colors - see: https://code.visualstudio.com/api/references/theme-color#base-colors
      'focusBorder': primary.hex(),
      'foreground': text.hex(),
      'disabledForeground': ease(text, 0.6).hex(),
      'widget.border': ease(background, 0.12).hex(),
      'widget.shadow': shadow,
      'selection.background': primary.alpha(0.24).hexa(),
      'descriptionForeground': ease(text, 0.4).hex(),
      'errorForeground': error.hex(),
      'icon.foreground': text.hex(),
      'sash.hoverBorder': secondary.hex(),

      // Window Border - see: https://code.visualstudio.com/api/references/theme-color#window-border
      // 'window.activeBorder': undefined,
      // 'window.inactiveBorder': undefined,

      // Text Colors - see: https://code.visualstudio.com/api/references/theme-color#text-colors
      'textBlockQuote.background': secondary.alpha(0.03).hexa(),
      'textBlockQuote.border': secondary.hex(),
      'textCodeBlock.background': text.alpha(0.15).hexa(),
      'textLink.activeForeground': primary.hex(),
      'textLink.foreground': ease(primary, 0.05).hex(),
      'textPreformat.foreground': text.hex(),
      'textPreformat.background': text.alpha(0.15).hexa(),
      // 'textPreformat.border': undefined,
      'textSeparator.foreground': text.hex(),

      // Action Colors - see: https://code.visualstudio.com/api/references/theme-color#action-colors
      'toolbar.hoverBackground': text.alpha(0.15).hexa(),
      'toolbar.hoverOutline': text.alpha(0).hexa(),
      'toolbar.activeBackground': text.alpha(0.25).hexa(),
      'editorActionList.background': ease(background, 0).hex(),
      'editorActionList.foreground': text.hex(),
      'editorActionList.focusForeground': text.hex(),
      'editorActionList.focusBackground': ease(background, 0.06).hex(),

      // Button Control - see: https://code.visualstudio.com/api/references/theme-color#button-control
      'button.background': ease(primary, 0.05).hex(),
      'button.foreground': contrast(primary).hex(),
      'button.border': primary.hex(),
      'button.separator': contrast(primary).alpha(0.2).hexa(),
      'button.hoverBackground': primary.hex(),
      'button.secondaryForeground': contrast(secondary).hex(),
      'button.secondaryBackground': ease(secondary, 0.05).hex(),
      'button.secondaryHoverBackground': secondary.hex(),
      // 'button.secondaryBorder': undefined,
      'checkbox.background': ease(background, 0.06).hex(),
      'checkbox.foreground': text.hex(),
      // 'checkbox.disabled.background': undefined,
      // 'checkbox.disabled.foreground': undefined,
      'checkbox.border': ease(background, 0.12).hex(),
      'checkbox.selectBackground': DEBUG,
      'checkbox.selectBorder': DEBUG,
      'radio.activeForeground': text.hex(),
      'radio.activeBackground': ease(primary, 0.8).hex(),
      'radio.activeBorder': primary.hex(),
      'radio.inactiveForeground': text.hex(),
      'radio.inactiveBackground': ease(background, 0.06).hex(),
      'radio.inactiveBorder': ease(background, 0.12).hex(),
      'radio.inactiveHoverBackground': ease(background, 0.12).hex(),

      // Dropdown Control - see: https://code.visualstudio.com/api/references/theme-color#dropdown-control
      'dropdown.background': ease(background, 0.06).hex(),
      'dropdown.listBackground': ease(background, 0.06).hex(),
      'dropdown.border': ease(background, 0.12).hex(),
      'dropdown.foreground': text.hex(),

      // Input Control - see: https://code.visualstudio.com/api/references/theme-color#input-control
      'input.background': ease(background, 0.06).hex(),
      'input.border': ease(background, 0.12).hex(),
      'input.foreground': text.hex(),
      'input.placeholderForeground': text.alpha(0.4).hexa(),
      'inputOption.activeBackground': text.alpha(0.25).hexa(),
      'inputOption.activeBorder': text.alpha(0).hexa(),
      'inputOption.activeForeground': text.hex(),
      'inputOption.hoverBackground': text.alpha(0.15).hexa(),
      'inputValidation.errorBackground': ease(background, 0.06).hex(),
      'inputValidation.errorForeground': error.hex(),
      'inputValidation.errorBorder': error.hex(),
      'inputValidation.infoBackground': ease(background, 0.06).hex(),
      'inputValidation.infoForeground': info.hex(),
      'inputValidation.infoBorder': info.hex(),
      'inputValidation.warningBackground': ease(background, 0.06).hex(),
      'inputValidation.warningForeground': warning.hex(),
      'inputValidation.warningBorder': warning.hex(),

      // Scrollbar Control - see: https://code.visualstudio.com/api/references/theme-color#scrollbar-control
      // 'scrollbar.background': undefined,
      'scrollbar.shadow': shadow,
      'scrollbarSlider.activeBackground': secondary.hex(),
      'scrollbarSlider.background': secondary.alpha(0.1).hexa(),
      'scrollbarSlider.hoverBackground': secondary.alpha(0.15).hexa(),

      // Badge - see: https://code.visualstudio.com/api/references/theme-color#badge
      'badge.foreground': contrast(primary).hex(),
      'badge.background': primary.hex(),

      // Progress Bar - see: https://code.visualstudio.com/api/references/theme-color#progress-bar
      'progressBar.background': primary.hex(),

      // Lists and Trees - see: https://code.visualstudio.com/api/references/theme-color#lists-and-trees
      'list.activeSelectionBackground': primary.alpha(0.1).hexa(),
      'list.activeSelectionForeground': text.hex(),
      'list.activeSelectionIconForeground': text.hex(),
      'list.dropBackground': secondary.alpha(0.1).hexa(),
      'list.focusBackground': primary.alpha(0.1).hexa(),
      'list.focusForeground': text.hex(),
      'list.focusHighlightForeground': text.hex(),
      'list.focusOutline': primary.hex(),
      'list.focusAndSelectionOutline': primary.hex(),
      'list.highlightForeground': text.hex(),
      'list.hoverBackground': primary.alpha(0.1).hexa(),
      'list.hoverForeground': text.hex(),
      'list.inactiveSelectionBackground': primary.alpha(0.1).hexa(),
      'list.inactiveSelectionForeground': text.hex(),
      'list.inactiveSelectionIconForeground': text.hex(),
      'list.inactiveFocusBackground': primary.alpha(0.1).hexa(),
      'list.inactiveFocusOutline': primary.alpha(0).hexa(),
      'list.invalidItemForeground': error.hex(),
      'list.errorForeground': error.hex(),
      'list.warningForeground': warning.hex(),
      'listFilterWidget.background': DEBUG,
      'listFilterWidget.outline': DEBUG,
      'listFilterWidget.noMatchesOutline': DEBUG,
      'listFilterWidget.shadow': DEBUG,
      'list.filterMatchBackground': DEBUG,
      'list.filterMatchBorder': DEBUG,
      'list.deemphasizedForeground': ease(text, 0.4).hex(),
      'list.dropBetweenBackground': secondary.alpha(0.1).hexa(),
      'tree.indentGuidesStroke': primary.alpha(0.15).hexa(),
      'tree.inactiveIndentGuidesStroke': primary.alpha(0.1).hexa(),
      'tree.tableColumnsBorder': ease(background, 0.08).hex(),
      'tree.tableOddRowsBackground': ease(background, 0.04).hex(),

      // Activity Bar - see: https://code.visualstudio.com/api/references/theme-color#activity-bar
      'activityBar.background': background.hex(),
      'activityBar.dropBorder': secondary.hex(),
      'activityBar.foreground': text.hex(),
      'activityBar.inactiveForeground': ease(text, 0.6).hex(),
      'activityBar.border': ease(background, 0.08).hex(),
      'activityBarBadge.background': primary.hex(),
      'activityBarBadge.foreground': contrast(primary).hex(),
      'activityBar.activeBorder': DEBUG,
      'activityBar.activeBackground': DEBUG,
      'activityBar.activeFocusBorder': DEBUG,
      'activityBarTop.foreground': text.hex(),
      'activityBarTop.activeBorder': DEBUG,
      'activityBarTop.inactiveForeground': ease(text, 0.6).hex(),
      'activityBarTop.dropBorder': secondary.hex(),
      'activityBarTop.background': background.hex(),
      'activityBarTop.activeBackground': background.hex(),
      'activityWarningBadge.foreground': contrast(warning).hex(),
      'activityWarningBadge.background': warning.hex(),
      'activityErrorBadge.foreground': contrast(error).hex(),
      'activityErrorBadge.background': error.hex(),

      // Profiles - see: https://code.visualstudio.com/api/references/theme-color#profiles
      'profileBadge.background': DEBUG,
      'profileBadge.foreground': DEBUG,
      'profiles.sashBorder': ease(background, 0.12).hex(),

      // Side Bar - see: https://code.visualstudio.com/api/references/theme-color#side-bar
      'sideBar.background': background.hex(),
      'sideBar.foreground': text.hex(),
      'sideBar.border': ease(background, 0.08).hex(),
      'sideBar.dropBackground': secondary.alpha(0.1).hexa(),
      'sideBarTitle.foreground': text.hex(),
      'sideBarSectionHeader.background': background.hex(),
      'sideBarSectionHeader.foreground': text.hex(),
      'sideBarSectionHeader.border': ease(background, 0.08).hex(),
      'sideBarActivityBarTop.border': ease(background, 0.08).hex(),
      'sideBarTitle.background': background.hex(),
      'sideBarTitle.border': ease(background, 0.08).hex(),
      'sideBarStickyScroll.background': background.hex(),
      'sideBarStickyScroll.border': background.alpha(0).hexa(),
      'sideBarStickyScroll.shadow': shadow,

      // Minimap - see: https://code.visualstudio.com/api/references/theme-color#minimap
      'minimap.findMatchHighlight': primary.alpha(0.6).hexa(),
      'minimap.selectionHighlight': primary.alpha(0.6).hexa(),
      'minimap.errorHighlight': error.alpha(0.6).hexa(),
      'minimap.warningHighlight': warning.alpha(0.6).hexa(),
      'minimap.background': background.hex(),
      'minimap.selectionOccurrenceHighlight': primary.alpha(0.6).hexa(),
      'minimap.foregroundOpacity': text.alpha(0.6).hexa(),
      'minimap.infoHighlight': info.alpha(0.6).hexa(),
      'minimapSlider.background': contrast(background).alpha(0.1).hexa(),
      'minimapSlider.hoverBackground': contrast(background).alpha(0.15).hexa(),
      'minimapSlider.activeBackground': contrast(background).alpha(0.25).hexa(),
      'minimapGutter.addedBackground': added.hex(),
      'minimapGutter.modifiedBackground': modified.hex(),
      'minimapGutter.deletedBackground': deleted.hex(),

      // Editor Groups & Tabs - see: https://code.visualstudio.com/api/references/theme-color#editor-groups-tabs
      'editorGroup.border': ease(background, 0.08).hex(),
      'editorGroup.dropBackground': secondary.alpha(0.1).hexa(),
      'editorGroupHeader.noTabsBackground': background.hex(),
      'editorGroupHeader.tabsBackground': background.hex(),
      'editorGroupHeader.tabsBorder': ease(background, 0.08).hex(),
      'editorGroupHeader.border': ease(background, 0.08).hex(),
      'editorGroup.emptyBackground': background.hex(),
      'editorGroup.focusedEmptyBorder': ease(background, 0.08).hex(),
      'editorGroup.dropIntoPromptForeground': text.hex(),
      'editorGroup.dropIntoPromptBackground': ease(background, 0.06).hex(),
      'editorGroup.dropIntoPromptBorder': ease(background, 0.12).hex(),
      'tab.activeBackground': background.hex(),
      'tab.unfocusedActiveBackground': background.hex(),
      'tab.activeForeground': text.hex(),
      'tab.border': ease(background, 0.12).hex(),
      'tab.activeBorder': primary.hex(),
      'tab.selectedBorderTop': primary.alpha(0).hexa(),
      'tab.selectedBackground': background.hex(),
      'tab.selectedForeground': text.hex(),
      'tab.dragAndDropBorder': secondary.hex(),
      'tab.unfocusedActiveBorder': primary.hex(),
      'tab.activeBorderTop': primary.alpha(0).hexa(),
      'tab.unfocusedActiveBorderTop': primary.alpha(0).hexa(),
      'tab.lastPinnedBorder': ease(background, 0.12).hex(),
      'tab.inactiveBackground': ease(background, 0.06).hex(),
      'tab.unfocusedInactiveBackground': ease(background, 0.06).hex(),
      'tab.inactiveForeground': text.alpha(0.6).hexa(),
      'tab.unfocusedActiveForeground': text.hex(),
      'tab.unfocusedInactiveForeground': ease(text, 0.6).hex(),
      'tab.hoverBackground': ease(background, 0.06).hex(),
      'tab.unfocusedHoverBackground': ease(background, 0.06).hex(),
      'tab.hoverForeground': text.hex(),
      'tab.unfocusedHoverForeground': text.hex(),
      // 'tab.hoverBorder': undefined,
      // 'tab.unfocusedHoverBorder': undefined,
      'tab.activeModifiedBorder': DEBUG,
      'tab.inactiveModifiedBorder': DEBUG,
      'tab.unfocusedActiveModifiedBorder': DEBUG,
      'tab.unfocusedInactiveModifiedBorder': DEBUG,
      'editorPane.background': background.hex(),
      'sideBySideEditor.horizontalBorder': ease(background, 0.08).hex(),
      'sideBySideEditor.verticalBorder': ease(background, 0.08).hex(),

      // Editor Colors - see: https://code.visualstudio.com/api/references/theme-color#editor-colors
      'editor.background': background.hex(),
      'editor.foreground': text.hex(),
      'editorLineNumber.foreground': secondary.alpha(0.5).hexa(),
      'editorLineNumber.activeForeground': secondary.hex(),
      'editorLineNumber.dimmedForeground': secondary.alpha(0.5).hexa(),
      'editorCursor.background': ease(primary, 0.12).hex(),
      'editorCursor.foreground': ease(primary, 0.12).hex(),
      'editorMultiCursor.primary.foreground': DEBUG,
      'editorMultiCursor.primary.background': DEBUG,
      'editorMultiCursor.secondary.foreground': DEBUG,
      'editorMultiCursor.secondary.background': DEBUG,
      'editor.placeholder.foreground': text.alpha(0.4).hexa(),
      'editor.compositionBorder': DEBUG,
      'editor.selectionBackground': primary.alpha(0.24).hexa(),
      'editor.selectionForeground': text.hex(),
      'editor.inactiveSelectionBackground': primary.alpha(0.24).hexa(),
      'editor.selectionHighlightBackground': primary.alpha(0.1).hexa(),
      'editor.selectionHighlightBorder': primary.hex(),
      'editor.wordHighlightBackground': primary.alpha(0.1).hexa(),
      'editor.wordHighlightBorder': primary.alpha(0).hexa(),
      'editor.wordHighlightStrongBackground': primary.alpha(0.1).hexa(),
      'editor.wordHighlightStrongBorder': primary.alpha(0).hexa(),
      'editor.wordHighlightTextBackground': primary.alpha(0.1).hexa(),
      'editor.wordHighlightTextBorder': primary.alpha(0).hexa(),
      'editor.findMatchBackground': primary.alpha(0.2).hexa(),
      'editor.findMatchForeground': text.hex(),
      'editor.findMatchHighlightForeground': text.hex(),
      'editor.findMatchHighlightBackground': primary.alpha(0.2).hexa(),
      'editor.findRangeHighlightBackground': primary.alpha(0).hexa(),
      'editor.findMatchBorder': primary.hex(),
      'editor.findMatchHighlightBorder': primary.alpha(0).hexa(),
      'editor.findRangeHighlightBorder': primary.alpha(0).hexa(),
      'search.resultsInfoForeground': ease(text, 0.4).hex(),
      'searchEditor.findMatchBackground': DEBUG,
      'searchEditor.findMatchBorder': DEBUG,
      'searchEditor.textInputBorder': DEBUG,
      'editor.hoverHighlightBackground': primary.alpha(0.1).hexa(),
      'editor.lineHighlightBackground': secondary.alpha(0.1).hexa(),
      // 'editor.inactiveLineHighlightBackground': undefined,
      'editor.lineHighlightBorder': secondary.alpha(0).hexa(),
      'editorUnicodeHighlight.border': DEBUG,
      'editorUnicodeHighlight.background': DEBUG,
      'editorLink.activeForeground': primary.hex(),
      'editor.rangeHighlightBackground': primary.alpha(0).hexa(),
      'editor.rangeHighlightBorder': primary.alpha(0).hexa(),
      'editor.symbolHighlightBackground': DEBUG,
      'editor.symbolHighlightBorder': DEBUG,
      'editorWhitespace.foreground': text.alpha(0.2).hexa(),
      // 'editorIndentGuide.background': undefined,
      'editorIndentGuide.background1': primary.alpha(0.15).hexa(),
      // 'editorIndentGuide.background2': undefined,
      // 'editorIndentGuide.background3': undefined,
      // 'editorIndentGuide.background4': undefined,
      // 'editorIndentGuide.background5': undefined,
      // 'editorIndentGuide.background6': undefined,
      // 'editorIndentGuide.activeBackground': undefined,
      'editorIndentGuide.activeBackground1': primary.alpha(0.15).hexa(),
      // 'editorIndentGuide.activeBackground2': undefined,
      // 'editorIndentGuide.activeBackground3': undefined,
      // 'editorIndentGuide.activeBackground4': undefined,
      // 'editorIndentGuide.activeBackground5': undefined,
      // 'editorIndentGuide.activeBackground6': undefined,
      'editorInlayHint.background': DEBUG,
      'editorInlayHint.foreground': DEBUG,
      'editorInlayHint.typeForeground': DEBUG,
      'editorInlayHint.typeBackground': DEBUG,
      'editorInlayHint.parameterForeground': DEBUG,
      'editorInlayHint.parameterBackground': DEBUG,
      'editorRuler.foreground': text.hex(),
      'editor.linkedEditingBackground': DEBUG,
      'editorCodeLens.foreground': secondary.hex(),
      'editorLightBulb.foreground': secondary.hex(),
      'editorLightBulbAutoFix.foreground': secondary.hex(),
      'editorLightBulbAi.foreground': secondary.hex(),
      'editorBracketMatch.background': primary.alpha(0).hexa(),
      'editorBracketMatch.border': primary.alpha(0.3).hexa(),
      // 'editorBracketMatch.foreground': undefined,
      'editorBracketHighlight.foreground1': DEBUG,
      'editorBracketHighlight.foreground2': DEBUG,
      'editorBracketHighlight.foreground3': DEBUG,
      'editorBracketHighlight.foreground4': DEBUG,
      'editorBracketHighlight.foreground5': DEBUG,
      'editorBracketHighlight.foreground6': DEBUG,
      'editorBracketHighlight.unexpectedBracket.foreground': error.hex(),
      'editorBracketPairGuide.activeBackground1': DEBUG,
      'editorBracketPairGuide.activeBackground2': DEBUG,
      'editorBracketPairGuide.activeBackground3': DEBUG,
      'editorBracketPairGuide.activeBackground4': DEBUG,
      'editorBracketPairGuide.activeBackground5': DEBUG,
      'editorBracketPairGuide.activeBackground6': DEBUG,
      'editorBracketPairGuide.background1': DEBUG,
      'editorBracketPairGuide.background2': DEBUG,
      'editorBracketPairGuide.background3': DEBUG,
      'editorBracketPairGuide.background4': DEBUG,
      'editorBracketPairGuide.background5': DEBUG,
      'editorBracketPairGuide.background6': DEBUG,
      'editor.foldBackground': secondary.alpha(0.1).hexa(),
      'editor.foldPlaceholderForeground': text.alpha(0.4).hexa(),
      'editorOverviewRuler.background': background.hex(),
      'editorOverviewRuler.border': ease(background, 0.12).hex(),
      'editorOverviewRuler.findMatchForeground': primary.hex(),
      'editorOverviewRuler.rangeHighlightForeground': primary.alpha(0).hexa(),
      'editorOverviewRuler.selectionHighlightForeground': primary.alpha(0).hexa(),
      'editorOverviewRuler.wordHighlightForeground': primary.alpha(0).hexa(),
      'editorOverviewRuler.wordHighlightStrongForeground': primary.alpha(0).hexa(),
      'editorOverviewRuler.wordHighlightTextForeground': primary.alpha(0).hexa(),
      'editorOverviewRuler.modifiedForeground': modified.hex(),
      'editorOverviewRuler.addedForeground': added.hex(),
      'editorOverviewRuler.deletedForeground': deleted.hex(),
      'editorOverviewRuler.errorForeground': error.hex(),
      'editorOverviewRuler.warningForeground': warning.hex(),
      'editorOverviewRuler.infoForeground': info.hex(),
      'editorOverviewRuler.bracketMatchForeground': primary.hex(),
      // 'editorOverviewRuler.inlineChatInserted': undefined,
      // 'editorOverviewRuler.inlineChatRemoved': undefined,
      // 'editorOverviewRuler.commentDraftForeground': undefined,
      'editorError.foreground': error.hex(),
      'editorError.border': error.alpha(0).hexa(),
      'editorError.background': error.alpha(0).hexa(),
      'editorWarning.foreground': warning.hex(),
      'editorWarning.border': warning.alpha(0).hexa(),
      'editorWarning.background': warning.alpha(0).hexa(),
      'editorInfo.foreground': info.hex(),
      'editorInfo.border': info.alpha(0).hexa(),
      'editorInfo.background': info.alpha(0).hexa(),
      'editorHint.foreground': secondary.hex(),
      'editorHint.border': secondary.alpha(0).hexa(),
      'problemsErrorIcon.foreground': error.hex(),
      'problemsWarningIcon.foreground': warning.hex(),
      'problemsInfoIcon.foreground': info.hex(),
      'editorUnnecessaryCode.border': text.alpha(0).hexa(),
      'editorUnnecessaryCode.opacity': text.alpha(0.4).hexa(),
      'editorGutter.background': background.hex(),
      'editorGutter.modifiedBackground': modified.hex(),
      // 'editorGutter.modifiedSecondaryBackground': undefined,
      'editorGutter.addedBackground': added.hex(),
      // 'editorGutter.addedSecondaryBackground': undefined,
      'editorGutter.deletedBackground': deleted.hex(),
      // 'editorGutter.deletedSecondaryBackground': undefined,
      'editorGutter.commentRangeForeground': DEBUG,
      'editorGutter.commentGlyphForeground': DEBUG,
      'editorGutter.commentUnresolvedGlyphForeground': DEBUG,
      'editorGutter.foldingControlForeground': secondary.hex(),
      'editorGutter.itemGlyphForeground': text.hex(),
      'editorGutter.itemBackground': ease(background, 0.24).hex(),
      // 'editorGutter.commentDraftGlyphForeground': undefined,
      'editorCommentsWidget.resolvedBorder': DEBUG,
      'editorCommentsWidget.unresolvedBorder': DEBUG,
      'editorCommentsWidget.rangeBackground': DEBUG,
      'editorCommentsWidget.rangeActiveBackground': DEBUG,
      'editorCommentsWidget.replyInputBackground': DEBUG,
      'inlineEdit.gutterIndicator.primaryBorder': DEBUG,
      'inlineEdit.gutterIndicator.primaryForeground': DEBUG,
      'inlineEdit.gutterIndicator.primaryBackground': DEBUG,
      'inlineEdit.gutterIndicator.secondaryBorder': DEBUG,
      'inlineEdit.gutterIndicator.secondaryForeground': DEBUG,
      'inlineEdit.gutterIndicator.secondaryBackground': DEBUG,
      'inlineEdit.gutterIndicator.successfulBorder': DEBUG,
      'inlineEdit.gutterIndicator.successfulForeground': DEBUG,
      'inlineEdit.gutterIndicator.successfulBackground': DEBUG,
      'inlineEdit.gutterIndicator.background': DEBUG,
      'inlineEdit.originalBackground': DEBUG,
      'inlineEdit.modifiedBackground': DEBUG,
      'inlineEdit.originalChangedLineBackground': DEBUG,
      'inlineEdit.originalChangedTextBackground': DEBUG,
      'inlineEdit.modifiedChangedLineBackground': DEBUG,
      'inlineEdit.modifiedChangedTextBackground': DEBUG,
      'inlineEdit.originalBorder': DEBUG,
      'inlineEdit.modifiedBorder': DEBUG,
      'inlineEdit.tabWillAcceptModifiedBorder': DEBUG,
      'inlineEdit.tabWillAcceptOriginalBorder': DEBUG,

      // Diff Editor Colors - see: https://code.visualstudio.com/api/references/theme-color#diff-editor-colors
      'diffEditor.insertedTextBackground': added.alpha(0.2).hexa(),
      'diffEditor.insertedTextBorder': added.alpha(0).hexa(),
      'diffEditor.removedTextBackground': deleted.alpha(0.2).hexa(),
      'diffEditor.removedTextBorder': deleted.alpha(0).hexa(),
      'diffEditor.border': ease(background, 0.08).hex(),
      'diffEditor.diagonalFill': secondary.hex(),
      'diffEditor.insertedLineBackground': added.alpha(0.2).hexa(),
      'diffEditor.removedLineBackground': deleted.alpha(0.2).hexa(),
      'diffEditorGutter.insertedLineBackground': added.alpha(0.2).hexa(),
      'diffEditorGutter.removedLineBackground': deleted.alpha(0.2).hexa(),
      'diffEditorOverview.insertedForeground': added.hex(),
      'diffEditorOverview.removedForeground': deleted.hex(),
      'diffEditor.unchangedRegionBackground': secondary.alpha(0).hexa(),
      'diffEditor.unchangedRegionForeground': text.hex(),
      'diffEditor.unchangedRegionShadow': shadow,
      'diffEditor.unchangedCodeBackground': secondary.alpha(0).hexa(),
      'diffEditor.move.border': DEBUG,
      'diffEditor.moveActive.border': DEBUG,
      'multiDiffEditor.headerBackground': ease(background, 0.06).hex(),
      'multiDiffEditor.background': background.hex(),
      'multiDiffEditor.border': ease(background, 0.08).hex(),

      // Chat Colors - see: https://code.visualstudio.com/api/references/theme-color#chat-colors
      // 'chat.requestBorder': undefined,
      // 'chat.requestBackground': undefined,
      // 'chat.slashCommandBackground': undefined,
      // 'chat.slashCommandForeground': undefined,
      // 'chat.avatarBackground': undefined,
      // 'chat.avatarForeground': undefined,
      // 'chat.editedFileForeground': undefined,
      // 'chat.linesAddedForeground': undefined,
      // 'chat.linesRemovedForeground': undefined,
      // 'chat.requestCodeBorder': undefined,
      // 'chat.requestBubbleBackground': undefined,
      // 'chat.requestBubbleHoverBackground': undefined,
      // 'chat.checkpointSeparator': undefined,
      // 'chat.thinkingShimmer': undefined,
      // 'chatManagement.sashBorder': undefined,

      // Inline Chat Colors - see: https://code.visualstudio.com/api/references/theme-color#inline-chat-colors
      // 'inlineChat.background': undefined,
      // 'inlineChat.foreground': undefined,
      // 'inlineChat.border': undefined,
      // 'inlineChat.shadow': undefined,
      // 'inlineChatInput.border': undefined,
      // 'inlineChatInput.focusBorder': undefined,
      // 'inlineChatInput.placeholderForeground': undefined,
      // 'inlineChatInput.background': undefined,
      // 'inlineChatDiff.inserted': undefined,
      // 'inlineChatDiff.removed': undefined,

      // Panel Chat Colors - see: https://code.visualstudio.com/api/references/theme-color#panel-chat-colors
      'interactive.activeCodeBorder': DEBUG,
      'interactive.inactiveCodeBorder': DEBUG,

      // Editor Widget Colors - see: https://code.visualstudio.com/api/references/theme-color#editor-widget-colors
      'editorWidget.foreground': text.hex(),
      'editorWidget.background': ease(background, 0.06).hex(),
      'editorWidget.border': ease(background, 0.2).hex(),
      'editorWidget.resizeBorder': secondary.hex(),
      'editorSuggestWidget.background': ease(background, 0.06).hex(),
      'editorSuggestWidget.border': ease(background, 0.2).hex(),
      'editorSuggestWidget.foreground': text.hex(),
      'editorSuggestWidget.focusHighlightForeground': text.hex(),
      'editorSuggestWidget.highlightForeground': text.hex(),
      'editorSuggestWidget.selectedBackground': primary.alpha(0.15).hexa(),
      'editorSuggestWidget.selectedForeground': text.hex(),
      'editorSuggestWidget.selectedIconForeground': text.hex(),
      'editorSuggestWidgetStatus.foreground': text.hex(),
      'editorHoverWidget.foreground': text.hex(),
      'editorHoverWidget.background': ease(background, 0.06).hex(),
      'editorHoverWidget.border': ease(background, 0.2).hex(),
      'editorHoverWidget.highlightForeground': text.hex(),
      'editorHoverWidget.statusBarBackground': ease(background, 0.12).hex(),
      'editorGhostText.border': primary.alpha(0).hexa(),
      'editorGhostText.background': primary.alpha(0).hexa(),
      'editorGhostText.foreground': text.alpha(0.4).hexa(),
      'editorStickyScroll.background': background.hex(),
      'editorStickyScroll.border': background.alpha(0).hexa(),
      'editorStickyScroll.shadow': shadow,
      // 'editorStickyScrollGutter.background': undefined,
      'editorStickyScrollHover.background': primary.alpha(0.15).hexa(),
      'debugExceptionWidget.background': ease(background, 0.06).hex(),
      'debugExceptionWidget.border': error.hex(),
      'editorMarkerNavigation.background': background.hex(),
      'editorMarkerNavigationError.background': background.hex(),
      'editorMarkerNavigationWarning.background': background.hex(),
      'editorMarkerNavigationInfo.background': background.hex(),
      'editorMarkerNavigationError.headerBackground': ease(background, 0.06).hex(),
      'editorMarkerNavigationWarning.headerBackground': ease(background, 0.06).hex(),
      'editorMarkerNavigationInfo.headerBackground': ease(background, 0.06).hex(),

      // Peek View Colors - see: https://code.visualstudio.com/api/references/theme-color#peek-view-colors
      'peekView.border': primary.hex(),
      'peekViewEditor.background': background.hex(),
      'peekViewEditorGutter.background': background.hex(),
      'peekViewEditor.matchHighlightBackground': primary.alpha(0.2).hexa(),
      'peekViewEditor.matchHighlightBorder': primary.alpha(0).hexa(),
      'peekViewResult.background': background.hex(),
      'peekViewResult.fileForeground': text.hex(),
      'peekViewResult.lineForeground': text.hex(),
      'peekViewResult.matchHighlightBackground': primary.alpha(0.2).hexa(),
      'peekViewResult.selectionBackground': primary.alpha(0.15).hexa(),
      'peekViewResult.selectionForeground': text.hex(),
      'peekViewTitle.background': ease(background, 0.06).hex(),
      'peekViewTitleDescription.foreground': ease(text, 0.4).hex(),
      'peekViewTitleLabel.foreground': text.hex(),
      'peekViewEditorStickyScroll.background': background.hex(),
      // 'peekViewEditorStickyScrollGutter.background': undefined,

      // Merge Conflicts Colors - see: https://code.visualstudio.com/api/references/theme-color#merge-conflicts-colors
      'merge.currentHeaderBackground': modified.alpha(0.4).hexa(),
      'merge.currentContentBackground': modified.alpha(0.2).hexa(),
      'merge.incomingHeaderBackground': debug.alpha(0.4).hexa(),
      'merge.incomingContentBackground': debug.alpha(0.2).hexa(),
      'merge.border': background.alpha(0).hexa(),
      'merge.commonContentBackground': secondary.alpha(0.2).hexa(),
      'merge.commonHeaderBackground': secondary.alpha(0.4).hexa(),
      'editorOverviewRuler.currentContentForeground': modified.hex(),
      'editorOverviewRuler.incomingContentForeground': debug.hex(),
      'editorOverviewRuler.commonContentForeground': secondary.hex(),
      'editorOverviewRuler.commentForeground': DEBUG,
      'editorOverviewRuler.commentUnresolvedForeground': DEBUG,
      'mergeEditor.change.background': debug.alpha(0.2).hexa(),
      'mergeEditor.change.word.background': debug.alpha(0.25).hexa(),
      'mergeEditor.conflict.unhandledUnfocused.border': debug.hex(),
      'mergeEditor.conflict.unhandledFocused.border': debug.hex(),
      'mergeEditor.conflict.handledUnfocused.border': secondary.hex(),
      'mergeEditor.conflict.handledFocused.border': secondary.hex(),
      'mergeEditor.conflict.handled.minimapOverViewRuler': secondary.hex(),
      'mergeEditor.conflict.unhandled.minimapOverViewRuler': debug.hex(),
      'mergeEditor.conflictingLines.background': DEBUG,
      'mergeEditor.changeBase.background': DEBUG,
      'mergeEditor.changeBase.word.background': DEBUG,
      'mergeEditor.conflict.input1.background': DEBUG,
      'mergeEditor.conflict.input2.background': DEBUG,

      // Panel Colors - see: https://code.visualstudio.com/api/references/theme-color#panel-colors
      'panel.background': background.hex(),
      'panel.border': ease(background, 0.08).hex(),
      'panel.dropBorder': secondary.hex(),
      'panelTitle.activeBorder': ease(background, 0.08).hex(),
      'panelTitle.activeForeground': text.hex(),
      'panelTitle.inactiveForeground': text.hex(),
      'panelTitle.border': ease(background, 0.08).hex(),
      'panelTitleBadge.background': primary.hex(),
      'panelTitleBadge.foreground': contrast(primary).hex(),
      'panelInput.border': ease(background, 0.12).hex(),
      'panelSection.border': ease(background, 0.08).hex(),
      'panelSection.dropBackground': secondary.alpha(0.1).hexa(),
      'panelSectionHeader.background': background.hex(),
      'panelSectionHeader.foreground': text.hex(),
      'panelStickyScroll.background': background.hex(),
      'panelStickyScroll.border': background.alpha(0).hexa(),
      'panelStickyScroll.shadow': shadow,
      'panelSectionHeader.border': background.alpha(0).hexa(),
      'outputView.background': background.hex(),
      'outputViewStickyScroll.background': background.hex(),

      // Status Bar Colors - see: https://code.visualstudio.com/api/references/theme-color#status-bar-colors
      'statusBar.background': ease(background, 0.08).hex(),
      'statusBar.foreground': text.hex(),
      'statusBar.border': ease(background, 0.08).hex(),
      'statusBar.debuggingBackground': debug.hex(),
      'statusBar.debuggingForeground': text.hex(),
      'statusBar.debuggingBorder': debug.hex(),
      'statusBar.noFolderForeground': text.hex(),
      'statusBar.noFolderBackground': ease(background, 0.08).hex(),
      'statusBar.noFolderBorder': ease(background, 0.08).hex(),
      'statusBarItem.activeBackground': text.alpha(0.15).hexa(),
      'statusBarItem.hoverForeground': text.hex(),
      'statusBarItem.hoverBackground': text.alpha(0.1).hexa(),
      'statusBarItem.prominentForeground': text.hex(),
      'statusBarItem.prominentBackground': text.alpha(0.1).hexa(),
      'statusBarItem.prominentHoverForeground': text.hex(),
      'statusBarItem.prominentHoverBackground': text.alpha(0.1).hexa(),
      'statusBarItem.remoteBackground': primary.alpha(0).hexa(),
      'statusBarItem.remoteForeground': text.hex(),
      'statusBarItem.remoteHoverBackground': text.alpha(0.1).hexa(),
      'statusBarItem.remoteHoverForeground': text.hex(),
      'statusBarItem.errorBackground': error.alpha(0.4).hexa(),
      'statusBarItem.errorForeground': text.hex(),
      'statusBarItem.errorHoverBackground': error.alpha(0.4).hexa(),
      'statusBarItem.errorHoverForeground': text.hex(),
      'statusBarItem.warningBackground': warning.alpha(0.4).hexa(),
      'statusBarItem.warningForeground': text.hex(),
      'statusBarItem.warningHoverBackground': warning.alpha(0.4).hexa(),
      'statusBarItem.warningHoverForeground': text.hex(),
      'statusBarItem.compactHoverBackground': text.alpha(0.1).hexa(),
      'statusBarItem.focusBorder': primary.alpha(0).hexa(),
      'statusBar.focusBorder': ease(background, 0.08).hex(),
      'statusBarItem.offlineBackground': secondary.alpha(0.4).hexa(),
      'statusBarItem.offlineForeground': text.hex(),
      'statusBarItem.offlineHoverForeground': text.hex(),
      'statusBarItem.offlineHoverBackground': secondary.alpha(0.4).hexa(),

      // Title Bar Colors - see: https://code.visualstudio.com/api/references/theme-color#title-bar-colors
      'titleBar.activeBackground': background.hex(),
      'titleBar.activeForeground': text.hex(),
      'titleBar.inactiveBackground': background.hex(),
      'titleBar.inactiveForeground': ease(text, 0.6).hex(),
      'titleBar.border': ease(background, 0.08).hex(),

      // Menu Bar Colors - see: https://code.visualstudio.com/api/references/theme-color#menu-bar-colors
      'menubar.selectionForeground': DEBUG,
      'menubar.selectionBackground': DEBUG,
      'menubar.selectionBorder': DEBUG,
      'menu.foreground': DEBUG,
      'menu.background': DEBUG,
      'menu.selectionForeground': DEBUG,
      'menu.selectionBackground': DEBUG,
      'menu.selectionBorder': primary.hex(),
      'menu.separatorBackground': ease(background, 0.12).hex(),
      'menu.border': DEBUG,

      // Command Center Colors - see: https://code.visualstudio.com/api/references/theme-color#command-center-colors
      'commandCenter.foreground': text.hex(),
      'commandCenter.activeForeground': text.hex(),
      'commandCenter.background': background.hex(),
      'commandCenter.activeBackground': text.alpha(0.15).hexa(),
      'commandCenter.border': ease(background, 0.2).hex(),
      'commandCenter.inactiveForeground': text.hex(),
      'commandCenter.inactiveBorder': ease(background, 0.2).hex(),
      'commandCenter.activeBorder': primary.hex(),
      'commandCenter.debuggingBackground': DEBUG,

      // Notification Colors - see: https://code.visualstudio.com/api/references/theme-color#notification-colors
      'notificationCenter.border': ease(background, 0.12).hex(),
      'notificationCenterHeader.foreground': text.hex(),
      'notificationCenterHeader.background': ease(background, 0.06).hex(),
      'notificationToast.border': ease(background, 0.12).hex(),
      'notifications.foreground': text.hex(),
      'notifications.background': ease(background, 0.06).hex(),
      'notifications.border': ease(background, 0.12).hex(),
      'notificationLink.foreground': primary.hex(),
      'notificationsErrorIcon.foreground': error.hex(),
      'notificationsWarningIcon.foreground': warning.hex(),
      'notificationsInfoIcon.foreground': info.hex(),

      // Banner Colors - see: https://code.visualstudio.com/api/references/theme-color#banner-colors
      'banner.background': DEBUG,
      'banner.foreground': DEBUG,
      'banner.iconForeground': DEBUG,

      // Extensions Colors - see: https://code.visualstudio.com/api/references/theme-color#extensions-colors
      'extensionButton.prominentForeground': contrast(primary).hex(),
      'extensionButton.prominentBackground': ease(primary, 0.05).hex(),
      'extensionButton.prominentHoverBackground': primary.hex(),
      'extensionButton.background': ease(primary, 0.05).hex(),
      'extensionButton.foreground': contrast(primary).hex(),
      'extensionButton.hoverBackground': primary.hex(),
      'extensionButton.separator': contrast(primary).alpha(0.2).hexa(),
      // 'extensionButton.border': undefined,
      'extensionBadge.remoteBackground': primary.hex(),
      'extensionBadge.remoteForeground': contrast(primary).hex(),
      'extensionIcon.starForeground': primary.hex(),
      'extensionIcon.verifiedForeground': primary.hex(),
      'extensionIcon.preReleaseForeground': primary.hex(),
      'extensionIcon.sponsorForeground': primary.hex(),
      'extensionIcon.privateForeground': primary.hex(),
      // 'mcpIcon.starForeground': undefined,

      // Quick Picker Colors - see: https://code.visualstudio.com/api/references/theme-color#quick-picker-colors
      'pickerGroup.border': ease(background, 0.12).hex(),
      'pickerGroup.foreground': text.hex(),
      'quickInput.background': ease(background, 0.06).hex(),
      'quickInput.foreground': text.hex(),
      'quickInputList.focusBackground': primary.alpha(0.15).hexa(),
      'quickInputList.focusForeground': text.hex(),
      'quickInputList.focusIconForeground': text.hex(),
      'quickInputTitle.background': DEBUG,

      // Keybinding Label Colors - see: https://code.visualstudio.com/api/references/theme-color#keybinding-label-colors
      'keybindingLabel.background': ease(background, 0.18).hex(),
      'keybindingLabel.foreground': text.hex(),
      'keybindingLabel.border': ease(background, 0.36).hex(),
      'keybindingLabel.bottomBorder': ease(background, 0.24).hex(),

      // Keyboard Shortcut Table Colors - see: https://code.visualstudio.com/api/references/theme-color#keyboard-shortcut-table-colors
      'keybindingTable.headerBackground': background.hex(),
      'keybindingTable.rowsBackground': ease(background, 0.04).hex(),

      // Integrated Terminal Colors - see: https://code.visualstudio.com/api/references/theme-color#integrated-terminal-colors
      'terminal.background': background.hex(),
      'terminal.border': ease(background, 0.08).hex(),
      'terminal.foreground': text.hex(),
      'terminal.ansiBlack': color(terminal.black).hex(),
      'terminal.ansiBlue': color(terminal.blue).hex(),
      'terminal.ansiBrightBlack': color(terminal.brightBlack).hex(),
      'terminal.ansiBrightBlue': color(terminal.brightBlue).hex(),
      'terminal.ansiBrightCyan': color(terminal.brightCyan).hex(),
      'terminal.ansiBrightGreen': color(terminal.brightGreen).hex(),
      'terminal.ansiBrightMagenta': color(terminal.brightMagenta).hex(),
      'terminal.ansiBrightRed': color(terminal.brightRed).hex(),
      'terminal.ansiBrightWhite': color(terminal.brightWhite).hex(),
      'terminal.ansiBrightYellow': color(terminal.brightYellow).hex(),
      'terminal.ansiCyan': color(terminal.cyan).hex(),
      'terminal.ansiGreen': color(terminal.green).hex(),
      'terminal.ansiMagenta': color(terminal.magenta).hex(),
      'terminal.ansiRed': color(terminal.red).hex(),
      'terminal.ansiWhite': color(terminal.white).hex(),
      'terminal.ansiYellow': color(terminal.yellow).hex(),
      'terminal.selectionBackground': primary.alpha(0.24).hexa(),
      'terminal.selectionForeground': text.hex(),
      'terminal.inactiveSelectionBackground': primary.alpha(0.24).hexa(),
      'terminal.findMatchBackground': primary.alpha(0.2).hexa(),
      'terminal.findMatchBorder': primary.hex(),
      'terminal.findMatchHighlightBackground': primary.alpha(0.2).hexa(),
      'terminal.findMatchHighlightBorder': primary.alpha(0).hexa(),
      'terminal.hoverHighlightBackground': DEBUG,
      'terminalCursor.background': primary.hex(),
      'terminalCursor.foreground': primary.hex(),
      'terminal.dropBackground': secondary.alpha(0.1).hexa(),
      'terminal.tab.activeBorder': primary.hex(),
      'terminalCommandDecoration.defaultBackground': secondary.hex(),
      'terminalCommandDecoration.successBackground': secondary.hex(),
      'terminalCommandDecoration.errorBackground': error.hex(),
      'terminalOverviewRuler.cursorForeground': ease(primary, 0.12).hex(),
      'terminalOverviewRuler.findMatchForeground': primary.hex(),
      'terminalStickyScroll.background': background.hex(),
      'terminalStickyScroll.border': background.alpha(0).hexa(),
      'terminalStickyScrollHover.background': primary.alpha(0.15).hexa(),
      'terminal.initialHintForeground': DEBUG,
      'terminalOverviewRuler.border': ease(background, 0.08).hex(),
      'terminalCommandGuide.foreground': primary.alpha(0).hexa(),
      'terminalSymbolIcon.aliasForeground': DEBUG,
      // 'terminalSymbolIcon.branchForeground': undefined,
      // 'terminalSymbolIcon.commitForeground': undefined,
      'terminalSymbolIcon.flagForeground': DEBUG,
      'terminalSymbolIcon.optionForeground': DEBUG,
      'terminalSymbolIcon.optionValueForeground': DEBUG,
      'terminalSymbolIcon.methodForeground': DEBUG,
      'terminalSymbolIcon.argumentForeground': DEBUG,
      'terminalSymbolIcon.inlineSuggestionForeground': DEBUG,
      'terminalSymbolIcon.fileForeground': DEBUG,
      'terminalSymbolIcon.folderForeground': DEBUG,
      // 'terminalSymbolIcon.pullRequestDoneForeground': undefined,
      // 'terminalSymbolIcon.pullRequestForeground': undefined,
      // 'terminalSymbolIcon.remoteForeground': undefined,
      // 'terminalSymbolIcon.stashForeground': undefined,
      // 'terminalSymbolIcon.symbolText': undefined,
      // 'terminalSymbolIcon.symbolicLinkFileForeground': undefined,
      // 'terminalSymbolIcon.symbolicLinkFolderForeground': undefined,
      // 'terminalSymbolIcon.tagForeground': undefined,

      // Debug Colors - see: https://code.visualstudio.com/api/references/theme-color#debug-colors
      'debugToolBar.background': DEBUG,
      'debugToolBar.border': DEBUG,
      'editor.stackFrameHighlightBackground': DEBUG,
      'editor.focusedStackFrameHighlightBackground': DEBUG,
      'editor.inlineValuesForeground': DEBUG,
      'editor.inlineValuesBackground': DEBUG,
      'debugView.exceptionLabelForeground': DEBUG,
      'debugView.exceptionLabelBackground': DEBUG,
      'debugView.stateLabelForeground': DEBUG,
      'debugView.stateLabelBackground': DEBUG,
      'debugView.valueChangedHighlight': DEBUG,
      'debugTokenExpression.name': DEBUG,
      'debugTokenExpression.value': DEBUG,
      'debugTokenExpression.string': DEBUG,
      'debugTokenExpression.boolean': DEBUG,
      'debugTokenExpression.number': DEBUG,
      'debugTokenExpression.error': DEBUG,
      'debugTokenExpression.type': DEBUG,

      // Testing Colors - see: https://code.visualstudio.com/api/references/theme-color#testing-colors
      'testing.runAction': DEBUG,
      'testing.iconErrored': DEBUG,
      'testing.iconFailed': DEBUG,
      'testing.iconPassed': DEBUG,
      'testing.iconQueued': DEBUG,
      'testing.iconUnset': DEBUG,
      'testing.iconSkipped': DEBUG,
      'testing.iconErrored.retired': DEBUG,
      'testing.iconFailed.retired': DEBUG,
      'testing.iconPassed.retired': DEBUG,
      'testing.iconQueued.retired': DEBUG,
      'testing.iconUnset.retired': DEBUG,
      'testing.iconSkipped.retired': DEBUG,
      'testing.peekBorder': DEBUG,
      'testing.peekHeaderBackground': DEBUG,
      'testing.message.error.lineBackground': DEBUG,
      'testing.message.info.decorationForeground': DEBUG,
      'testing.message.info.lineBackground': DEBUG,
      'testing.messagePeekBorder': DEBUG,
      'testing.messagePeekHeaderBackground': DEBUG,
      'testing.coveredBackground': DEBUG,
      'testing.coveredBorder': DEBUG,
      'testing.coveredGutterBackground': DEBUG,
      'testing.uncoveredBranchBackground': DEBUG,
      'testing.uncoveredBackground': DEBUG,
      'testing.uncoveredBorder': DEBUG,
      'testing.uncoveredGutterBackground': DEBUG,
      'testing.coverCountBadgeBackground': DEBUG,
      'testing.coverCountBadgeForeground': DEBUG,
      'testing.message.error.badgeBackground': DEBUG,
      'testing.message.error.badgeBorder': DEBUG,
      'testing.message.error.badgeForeground': DEBUG,

      // Welcome Page Colors - see: https://code.visualstudio.com/api/references/theme-color#welcome-page-colors
      'welcomePage.background': DEBUG,
      'welcomePage.progress.background': DEBUG,
      'welcomePage.progress.foreground': DEBUG,
      'welcomePage.tileBackground': DEBUG,
      'welcomePage.tileHoverBackground': DEBUG,
      'welcomePage.tileBorder': DEBUG,
      // 'walkThrough.embeddedEditorBackground': undefined,
      'walkthrough.stepTitle.foreground': DEBUG,

      // Git Colors - see: https://code.visualstudio.com/api/references/theme-color#git-colors
      'gitDecoration.addedResourceForeground': added.hex(),
      'gitDecoration.modifiedResourceForeground': modified.hex(),
      'gitDecoration.deletedResourceForeground': deleted.hex(),
      'gitDecoration.renamedResourceForeground': added.hex(),
      'gitDecoration.stageModifiedResourceForeground': ease(modified, 0.2).hex(),
      'gitDecoration.stageDeletedResourceForeground': ease(deleted, 0.2).hex(),
      'gitDecoration.untrackedResourceForeground': ease(text, 0.4).hex(),
      'gitDecoration.ignoredResourceForeground': ease(text, 0.6).hex(),
      'gitDecoration.conflictingResourceForeground': debug.hex(),
      'gitDecoration.submoduleResourceForeground': ease(text, 0.4).hex(),
      'git.blame.editorDecorationForeground': DEBUG,

      // Source Control Graph Colors - see: https://code.visualstudio.com/api/references/theme-color#source-control-graph-colors
      'scmGraph.historyItemHoverLabelForeground': contrast(primary).hex(),
      'scmGraph.foreground1': color(terminal.blue).hex(),
      'scmGraph.foreground2': color(terminal.yellow).hex(),
      'scmGraph.foreground3': color(terminal.red).hex(),
      'scmGraph.foreground4': color(terminal.green).hex(),
      'scmGraph.foreground5': color(terminal.magenta).hex(),
      'scmGraph.historyItemHoverAdditionsForeground': added.hex(),
      'scmGraph.historyItemHoverDeletionsForeground': deleted.hex(),
      'scmGraph.historyItemRefColor': primary.hex(),
      'scmGraph.historyItemRemoteRefColor': info.hex(),
      'scmGraph.historyItemBaseRefColor': debug.hex(),
      'scmGraph.historyItemHoverDefaultLabelForeground': contrast(primary).hex(),
      'scmGraph.historyItemHoverDefaultLabelBackground': primary.hex(),

      // Settings Editor Colors - see: https://code.visualstudio.com/api/references/theme-color#settings-editor-colors
      'settings.headerForeground': text.hex(),
      'settings.modifiedItemIndicator': modified.hex(),
      'settings.dropdownBackground': ease(background, 0.06).hex(),
      'settings.dropdownForeground': text.hex(),
      'settings.dropdownBorder': ease(background, 0.12).hex(),
      'settings.dropdownListBorder': ease(background, 0.12).hex(),
      'settings.checkboxBackground': ease(background, 0.06).hex(),
      'settings.checkboxForeground': text.hex(),
      'settings.checkboxBorder': ease(background, 0.12).hex(),
      'settings.rowHoverBackground': ease(background, 0.04).hex(),
      'settings.textInputBackground': ease(background, 0.06).hex(),
      'settings.textInputForeground': text.hex(),
      'settings.textInputBorder': ease(background, 0.12).hex(),
      'settings.numberInputBackground': ease(background, 0.06).hex(),
      'settings.numberInputForeground': text.hex(),
      'settings.numberInputBorder': ease(background, 0.12).hex(),
      'settings.focusedRowBackground': ease(background, 0.04).hex(),
      'settings.focusedRowBorder': primary.hex(),
      'settings.headerBorder': ease(background, 0.12).hex(),
      'settings.sashBorder': ease(background, 0.12).hex(),
      'settings.settingsHeaderHoverForeground': text.hex(),

      // Breadcrumbs Colors - see: https://code.visualstudio.com/api/references/theme-color#breadcrumbs-colors
      'breadcrumb.foreground': text.hex(),
      'breadcrumb.background': background.hex(),
      'breadcrumb.focusForeground': text.hex(),
      'breadcrumb.activeSelectionForeground': text.hex(),
      'breadcrumbPicker.background': ease(background, 0.06).hex(),

      // Snippets Colors - see: https://code.visualstudio.com/api/references/theme-color#snippets-colors
      'editor.snippetTabstopHighlightBackground': primary.alpha(0.1).hexa(),
      'editor.snippetTabstopHighlightBorder': primary.hex(),
      'editor.snippetFinalTabstopHighlightBackground': primary.alpha(0.1).hexa(),
      'editor.snippetFinalTabstopHighlightBorder': primary.hex(),

      // Symbol Icons Colors - see: https://code.visualstudio.com/api/references/theme-color#symbol-icons-colors
      'symbolIcon.arrayForeground': secondary.hex(),
      'symbolIcon.booleanForeground': secondary.hex(),
      'symbolIcon.classForeground': secondary.hex(),
      'symbolIcon.colorForeground': secondary.hex(),
      'symbolIcon.constantForeground': secondary.hex(),
      'symbolIcon.constructorForeground': secondary.hex(),
      'symbolIcon.enumeratorForeground': secondary.hex(),
      'symbolIcon.enumeratorMemberForeground': secondary.hex(),
      'symbolIcon.eventForeground': secondary.hex(),
      'symbolIcon.fieldForeground': secondary.hex(),
      'symbolIcon.fileForeground': secondary.hex(),
      'symbolIcon.folderForeground': secondary.hex(),
      'symbolIcon.functionForeground': secondary.hex(),
      'symbolIcon.interfaceForeground': secondary.hex(),
      'symbolIcon.keyForeground': secondary.hex(),
      'symbolIcon.keywordForeground': secondary.hex(),
      'symbolIcon.methodForeground': secondary.hex(),
      'symbolIcon.moduleForeground': secondary.hex(),
      'symbolIcon.namespaceForeground': secondary.hex(),
      'symbolIcon.nullForeground': secondary.hex(),
      'symbolIcon.numberForeground': secondary.hex(),
      'symbolIcon.objectForeground': secondary.hex(),
      'symbolIcon.operatorForeground': secondary.hex(),
      'symbolIcon.packageForeground': secondary.hex(),
      'symbolIcon.propertyForeground': secondary.hex(),
      'symbolIcon.referenceForeground': secondary.hex(),
      'symbolIcon.snippetForeground': secondary.hex(),
      'symbolIcon.stringForeground': secondary.hex(),
      'symbolIcon.structForeground': secondary.hex(),
      'symbolIcon.textForeground': secondary.hex(),
      'symbolIcon.typeParameterForeground': secondary.hex(),
      'symbolIcon.unitForeground': secondary.hex(),
      'symbolIcon.variableForeground': secondary.hex(),

      // Debug Icons Colors - see: https://code.visualstudio.com/api/references/theme-color#debug-icons-colors
      'debugIcon.breakpointForeground': DEBUG,
      'debugIcon.breakpointDisabledForeground': DEBUG,
      'debugIcon.breakpointUnverifiedForeground': DEBUG,
      'debugIcon.breakpointCurrentStackframeForeground': DEBUG,
      'debugIcon.breakpointStackframeForeground': DEBUG,
      'debugIcon.startForeground': DEBUG,
      'debugIcon.pauseForeground': DEBUG,
      'debugIcon.stopForeground': DEBUG,
      'debugIcon.disconnectForeground': DEBUG,
      'debugIcon.restartForeground': DEBUG,
      'debugIcon.stepOverForeground': DEBUG,
      'debugIcon.stepIntoForeground': DEBUG,
      'debugIcon.stepOutForeground': DEBUG,
      'debugIcon.continueForeground': DEBUG,
      'debugIcon.stepBackForeground': DEBUG,
      'debugConsole.infoForeground': DEBUG,
      'debugConsole.warningForeground': DEBUG,
      'debugConsole.errorForeground': DEBUG,
      'debugConsole.sourceForeground': DEBUG,
      'debugConsoleInputIcon.foreground': DEBUG,

      // Notebook Colors - see: https://code.visualstudio.com/api/references/theme-color#notebook-colors
      'notebook.editorBackground': DEBUG,
      'notebook.cellBorderColor': DEBUG,
      'notebook.cellHoverBackground': DEBUG,
      'notebook.cellInsertionIndicator': DEBUG,
      'notebook.cellStatusBarItemHoverBackground': DEBUG,
      'notebook.cellToolbarSeparator': DEBUG,
      'notebook.cellEditorBackground': DEBUG,
      'notebook.focusedCellBackground': DEBUG,
      'notebook.focusedCellBorder': DEBUG,
      'notebook.focusedEditorBorder': DEBUG,
      'notebook.inactiveFocusedCellBorder': DEBUG,
      'notebook.inactiveSelectedCellBorder': DEBUG,
      'notebook.outputContainerBackgroundColor': DEBUG,
      'notebook.outputContainerBorderColor': DEBUG,
      'notebook.selectedCellBackground': DEBUG,
      'notebook.selectedCellBorder': DEBUG,
      'notebook.symbolHighlightBackground': DEBUG,
      'notebookScrollbarSlider.activeBackground': DEBUG,
      'notebookScrollbarSlider.background': DEBUG,
      'notebookScrollbarSlider.hoverBackground': DEBUG,
      'notebookStatusErrorIcon.foreground': DEBUG,
      'notebookStatusRunningIcon.foreground': DEBUG,
      'notebookStatusSuccessIcon.foreground': DEBUG,
      'notebookEditorOverviewRuler.runningCellForeground': DEBUG,

      // Chart Colors - see: https://code.visualstudio.com/api/references/theme-color#chart-colors
      'charts.foreground': text.hex(),
      'charts.lines': primary.hex(),
      'charts.red': color(terminal.red).hex(),
      'charts.blue': color(terminal.blue).hex(),
      'charts.yellow': color(terminal.yellow).hex(),
      'charts.orange': color(terminal.cyan).hex(),
      'charts.green': color(terminal.green).hex(),
      'charts.purple': color(terminal.magenta).hex(),
      'chart.line': primary.hex(),
      'chart.axis': text.hex(),
      'chart.guide': ease(background, 0.12).hex(),

      // Ports Colors - see: https://code.visualstudio.com/api/references/theme-color#ports-colors
      // 'ports.iconRunningProcessForeground': text.hex(),

      // Comments View Colors - see: https://code.visualstudio.com/api/references/theme-color#comments-view-colors
      'commentsView.resolvedIcon': DEBUG,
      'commentsView.unresolvedIcon': DEBUG,

      // Action Bar Colors - see: https://code.visualstudio.com/api/references/theme-color#action-bar-colors
      'actionBar.toggledBackground': DEBUG,

      // Simple Find Widget Colors - see: https://code.visualstudio.com/api/references/theme-color#simple-find-widget-colors
      'simpleFindWidget.sashBorder': DEBUG,

      // Gauge Colors - see: https://code.visualstudio.com/api/references/theme-color#gauge-colors
      // 'gauge.background': undefined,
      // 'gauge.foreground': undefined,
      // 'gauge.border': undefined,
      // 'gauge.warningBackground': undefined,
      // 'gauge.warningForeground': undefined,
      // 'gauge.errorBackground': undefined,
      // 'gauge.errorForeground': undefined,

      // Markdown - see: https://code.visualstudio.com/api/references/theme-color#markdown
      // 'markdownAlert.note.foreground': undefined,
      // 'markdownAlert.tip.foreground': undefined,
      // 'markdownAlert.important.foreground': undefined,
      // 'markdownAlert.warning.foreground': undefined,
      // 'markdownAlert.caution.foreground': undefined,

      // Agent Session Colors - see: https://code.visualstudio.com/api/references/theme-color#agent-session-colors
      // 'agentSessionReadIndicator.foreground': undefined,
      // 'agentSessionSelectedBadge.border': undefined,
      // 'agentSessionSelectedUnfocusedBadge.border': undefined,
      // 'agentStatusIndicator.background': undefined,

      // AI Customization Management
      // 'aiCustomizationManagement.sashBorder': undefined,
    },
    semanticHighlighting: true,
    semanticTokenColors: {},
    tokenColors: [
      {
        scope: 'source',
        settings: {
          foreground: color(tokens.default).hex(),
        },
      },
      {
        scope: [
          'entity.name.function.preprocessor',
          'keyword',
          'keyword.control',
          'keyword.operator.expression',
          'keyword.operator.new',
          'keyword.operator.sizeof',
          'keyword.other',
          'meta.preprocessor',
          'punctuation.definition.directive',
          'punctuation.definition.keyword',
          'punctuation.definition.storage.type',
          'storage.modifier',
          'storage.type',
        ],
        settings: {
          foreground: color(tokens.keyword).hex(),
        },
      },
      {
        scope: [
          'entity.name.function',
          'support.class.component',
          'support.function',
          'variable.function',
        ],
        settings: {
          foreground: color(tokens.function).hex(),
        },
      },
      {
        scope: [
          'constant',
          'constant.character',
          'constant.language',
          'constant.numeric',
          'entity.name.tag',
          'keyword.other.unit',
          'markup.inline.raw',
          'meta.preprocessor.numeric',
          'punctuation.definition.constant',
          'punctuation.definition.raw',
          'support.constant',
          'support.function.builtin',
          'variable.language',
        ],
        settings: {
          foreground: color(tokens.literal).hex(),
        },
      },
      {
        scope: [
          'constant.other.database-name',
          'constant.other.variable',
          'entity.name.command',
          'entity.name.variable',
          'variable',
          'variable.other',
          'variable.parameter',
        ],
        settings: {
          foreground: color(tokens.variable).hex(),
        },
      },
      {
        scope: [
          'constant.other.option',
          'constant.other.table-name',
          'entity.other.attribute-name',
          'meta.object-literal.key',
          'meta.object.member',
          'punctuation.support',
          'support.type.property-name',
          'variable.other.member',
          'variable.other.object.property',
          'variable.other.property',

          // yaml
          'entity.name.tag.yaml',
        ],
        settings: {
          foreground: color(tokens.attribute).hex(),
        },
      },
      {
        scope: [
          'entity.name.class',
          'entity.name.enum',
          'entity.name.interface',
          'entity.name.type',
          'entity.name.type.enum',
          'entity.name.type.interface',
          'entity.other.inherited-class',
          'support.type',

          // css
          'entity.other.attribute-name.class.css',
          'entity.other.attribute-name.id.css',
          'punctuation.definition.entity.css',
        ],
        settings: {
          foreground: color(tokens.type).hex(),
        },
      },
      {
        scope: ['entity.name.type.class', 'entity.name.type.module'],
        settings: {
          fontStyle: '',
        },
      },
      {
        scope: [
          'entity.name.type',
          'entity.other.inherited-class',
          'meta.protocol-list',
          'support.type.builtin',
          'support.type.posix-reserved',
          'support.type.primitive',
        ],
        settings: {
          fontStyle: 'italic',
        },
      },
      {
        scope: ['markup.heading', 'punctuation.definition.heading'],
        settings: {
          fontStyle: 'bold',
          foreground: color(tokens.keyword).hex(),
        },
      },
      {
        scope: ['markup.bold'],
        settings: {
          fontStyle: 'bold',
        },
      },
      {
        scope: ['markup.italic'],
        settings: {
          fontStyle: 'italic',
        },
      },
      {
        scope: ['markup.underline', 'markup.underline.link'],
        settings: {
          fontStyle: 'underline',
        },
      },
      {
        scope: ['markup.strikethrough'],
        settings: {
          fontStyle: 'strikethrough',
        },
      },
      {
        scope: ['markup.quote', 'markup.quote.markdown', 'punctuation.definition.quote'],
        settings: {
          foreground: ease(color(tokens.default), 0.3).hex(),
        },
      },
      {
        scope: [
          'punctuation.definition.string',
          'string',
          'string.quoted',
          'string.regexp',
          'string.template',
        ],
        settings: {
          foreground: color(tokens.string).hex(),
        },
      },
      {
        scope: ['comment', 'comment.block', 'comment.line', 'punctuation.definition.comment'],
        settings: {
          fontStyle: 'italic',
          foreground: color(tokens.comment).hex(),
        },
      },
      {
        scope: [
          'constant.language.import-export-all',
          'keyword.operator',
          'meta.brace',
          'punctuation',
          'punctuation.definition',
          'punctuation.section',
          'punctuation.separator',
          'punctuation.terminator',
          'storage.modifier.array',
          'storage.type.function.arrow',
        ],
        settings: {
          foreground: color(tokens.other).hex(),
        },
      },
      {
        scope: ['invalid.deprecated'],
        settings: {
          fontStyle: 'strikethrough',
        },
      },
    ],
  };
}
